---
- name: Include OS-specific tasks
  tags: ['basics', 'git', 'curl', 'wget', 'build-essential', 'zsh', 'tmux', 'ccze', 'direnv', 'redshift', 'xsel']
  include_tasks: "{{ ansible_distribution | lower }}.yml"
  when: ansible_distribution == "Ubuntu"
