---
- name: Setup Ubuntu Development Environment
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars/versions.yml
  vars:
    user_name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    user_home: "{{ lookup('env', 'SUDO_USER') | ternary('/home/' + lookup('env', 'SUDO_USER'), ansible_env.HOME) }}"

  tasks:
    - name: Include system role
      include_role:
        name: system
      tags:
        - always
        - system

    - name: Include basics role
      include_role:
        name: basics
      tags:
        - basics
        - git
        - curl
        - wget
        - build-essential
        - zsh
        - tmux
        - ccze
        - direnv
        - redshift
        - xsel

    - name: Include zsh role
      include_role:
        name: zsh
      tags:
        - zsh

    - name: Include fzf role
      include_role:
        name: fzf
      tags:
        - fzf

    - name: Include up role
      include_role:
        name: up
      tags:
        - up

    - name: Include ripgrep role
      include_role:
        name: ripgrep
      tags:
        - ripgrep
        - rg

    - name: Include espanso role
      include_role:
        name: espanso
      tags:
        - espanso

    - name: Include dust role
      include_role:
        name: dust
      tags:
        - dust

    - name: Include xh role
      include_role:
        name: xh
      tags:
        - xh

    - name: Include broot role
      include_role:
        name: broot
      tags:
        - broot

    - name: Include procs role
      include_role:
        name: procs
      tags:
        - procs

    - name: Include bottom role
      include_role:
        name: bottom
      tags:
        - bottom
        - btm

    - name: Include zellij role
      include_role:
        name: zellij
      tags:
        - zellij

    - name: Include gping role
      include_role:
        name: gping
      tags:
        - gping

    - name: Include bandwhich role
      include_role:
        name: bandwhich
      tags:
        - bandwhich

    - name: Include bat role
      include_role:
        name: bat
      tags:
        - bat

    - name: Include zoxide role
      include_role:
        name: zoxide
      tags:
        - zoxide

    - name: Include gitui role
      include_role:
        name: gitui
      tags:
        - gitui

    - name: Include asciinema role
      include_role:
        name: asciinema
      tags:
        - asciinema

    - name: Include navi role
      include_role:
        name: navi
      tags:
        - navi

    - name: Include ssh-list role
      include_role:
        name: ssh-list
      tags:
        - ssh-list

    - name: Include tldr role
      include_role:
        name: tldr
      tags:
        - tldr
        
    - name: Include nvm role
      include_role:
        name: nvm
      tags:
        - nvm

    - name: Include config role
      include_role:
        name: config
      tags:
        - config
        - zsh
        - tmux
        - direnv

  handlers:
    - name: reload shell
      debug:
        msg: "Shell configuration updated. Please restart your terminal or run 'source ~/.zshrc'"
