---
- name: Check if tldr is installed
  stat:
    path: /usr/local/bin/tldr
  register: tldr_stat

- name: Download and install tldr (tealdeer)
  block:
    - name: Download tealdeer binary
      get_url:
        url: "https://github.com/tealdeer-rs/tealdeer/releases/download/{{ tldr_version }}/tealdeer-linux-x86_64-musl"
        dest: /usr/local/bin/tldr
        mode: '0755'

    - name: Initialize tldr cache
      command: /usr/local/bin/tldr --update
      become: no
      become_user: "{{ user_name }}"
      changed_when: true
  when: not tldr_stat.stat.exists
