---
- name: Check if zoxide is installed
  tags: ["zoxide"]
  stat:
    path: /usr/local/bin/zoxide
  register: zoxide_stat

- name: Download and install zoxide
  tags: ["zoxide"]
  block:
    - name: Create temporary directory for zoxide
      tags: ["zoxide"]
      tempfile:
        state: directory
      register: zoxide_temp

    - name: Download zoxide tarball
      tags: ["zoxide"]
      get_url:
        url: "https://github.com/ajeetdsouza/zoxide/releases/download/v{{ zoxide_version }}/zoxide-{{ zoxide_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "{{ zoxide_temp.path }}/zoxide.tar.gz"

    - name: Extract zoxide tarball
      tags: ["zoxide"]
      unarchive:
        src: "{{ zoxide_temp.path }}/zoxide.tar.gz"
        dest: "{{ zoxide_temp.path }}"
        remote_src: yes

    - name: Find zoxide binary in extracted directory
      tags: ["zoxide"]
      find:
        paths: "{{ zoxide_temp.path }}"
        patterns: "zoxide"
        recurse: yes
        file_type: file
      register: zoxide_binary

    - name: Install zoxide to /usr/local/bin
      tags: ["zoxide"]
      copy:
        src: "{{ zoxide_binary.files[0].path }}"
        dest: /usr/local/bin/zoxide
        mode: '0755'
        remote_src: yes

    - name: Clean up zoxide temporary directory
      tags: ["zoxide"]
      file:
        path: "{{ zoxide_temp.path }}"
        state: absent
  when: not zoxide_stat.stat.exists
