---
- name: Clone fzf repository
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "{{ user_home }}/.fzf"
    version: "{{ fzf_version }}"
    depth: 1
    update: yes
  become: no

- name: Install fzf
  shell: "{{ user_home }}/.fzf/install --all --no-bash --no-fish"
  args:
    creates: "{{ user_home }}/.fzf/bin/fzf"
  become: no
