---
- name: Create config directory
  tags: ['config']
  file:
    path: "{{ user_home }}/.config"
    state: directory
    owner: "{{ user_name }}"
    mode: '0755'
  become: no

- name: Copy custom zshrc
  tags: ['config']
  template:
    src: ./configs/zshrc.j2
    dest: "{{ user_home }}/.zshrc"
    owner: "{{ user_name }}"
    mode: '0644'
  become: no
  # when: false  # Enable this when you create the config file

- name: Copy custom tmux.conf
  tags: ['config']
  template:
    src: ./configs/tmux.conf.j2
    dest: "{{ user_home }}/.tmux.conf"
    owner: "{{ user_name }}"
    mode: '0644'
  become: no
  # when: false  # Enable this when you create the config file

- name: Copy custom .p10k.zsh configuration
  tags: ['config']
  copy:
    src: ./configs/p10k.zsh
    dest: "{{ user_home }}/.p10k.zsh"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
    backup: yes
  become: no
  register: p10k_copy_result
  failed_when: false

- name: Setup direnv hook for zsh
  tags: ['config']
  lineinfile:
    path: "{{ user_home }}/.zshrc"
    line: 'eval "$(direnv hook zsh)"'
    create: yes
    owner: "{{ user_name }}"
  become: no
