---
- name: Check if dust is installed
  stat:
    path: /usr/local/bin/dust
  register: dust_stat

- name: Download and install dust
  block:
    - name: Create temporary directory for dust
      tempfile:
        state: directory
      register: dust_temp

    - name: Download dust tarball
      get_url:
        url: "https://github.com/bootandy/dust/releases/download/{{ dust_version }}/dust-{{ dust_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "{{ dust_temp.path }}/dust.tar.gz"

    - name: Extract dust tarball
      unarchive:
        src: "{{ dust_temp.path }}/dust.tar.gz"
        dest: "{{ dust_temp.path }}"
        remote_src: yes

    - name: Find dust binary in extracted directory
      find:
        paths: "{{ dust_temp.path }}"
        patterns: "dust"
        recurse: yes
        file_type: file
      register: dust_binary

    - name: Install dust to /usr/local/bin
      copy:
        src: "{{ dust_binary.files[0].path }}"
        dest: /usr/local/bin/dust
        mode: '0755'
        remote_src: yes

    - name: Clean up dust temporary directory
      file:
        path: "{{ dust_temp.path }}"
        state: absent
  when: not dust_stat.stat.exists
