---
- name: Check if zellij is installed
  tags: ['zellij']
  stat:
    path: /usr/local/bin/zellij
  register: zellij_stat

- name: Download and install zellij
  tags: ['zellij']
  block:
    - name: Create temporary directory for zellij
      tempfile:
        state: directory
      register: zellij_temp

    - name: Download zellij tarball
      get_url:
        url: "https://github.com/zellij-org/zellij/releases/download/{{ zellij_version }}/zellij-x86_64-unknown-linux-musl.tar.gz"
        dest: "{{ zellij_temp.path }}/zellij.tar.gz"

    - name: Extract zellij tarball
      unarchive:
        src: "{{ zellij_temp.path }}/zellij.tar.gz"
        dest: "{{ zellij_temp.path }}"
        remote_src: yes

    - name: Find zellij binary in extracted directory
      find:
        paths: "{{ zellij_temp.path }}"
        patterns: "zellij"
        recurse: yes
        file_type: file
      register: zellij_binary

    - name: Install zellij to /usr/local/bin
      copy:
        src: "{{ zellij_binary.files[0].path }}"
        dest: /usr/local/bin/zellij
        mode: '0755'
        remote_src: yes

    - name: Clean up zellij temporary directory
      file:
        path: "{{ zellij_temp.path }}"
        state: absent
  when: not zellij_stat.stat.exists
